
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.proyectofinalcompi1.AnalizadorSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int KEYWORDS = 4;
  public static final int DESCRIPTION = 3;
  public static final int CHART = 14;
  public static final int Y = 19;
  public static final int FONT_SIZE = 9;
  public static final int X = 18;
  public static final int LINE_STYLE = 23;
  public static final int LEGEND_POSITION = 17;
  public static final int DIFERENTE = 47;
  public static final int CATEGORY = 11;
  public static final int DOS_PUNTOS = 37;
  public static final int CORCHETE_C = 43;
  public static final int CORCHETE_A = 42;
  public static final int LLAVE_C = 41;
  public static final int ASTERISCO = 34;
  public static final int LLAVE_A = 40;
  public static final int FOR = 31;
  public static final int BACKGROUND_COLOR = 7;
  public static final int CONSTANTE = 60;
  public static final int Y_AXIS_LABEL = 16;
  public static final int DATA = 10;
  public static final int IDENTIFICADOR = 54;
  public static final int IGUAL = 48;
  public static final int POINTS = 22;
  public static final int SOLID = 24;
  public static final int IF = 29;
  public static final int IGUAL_IGUAL = 49;
  public static final int PUNTO_COMA = 36;
  public static final int EOF = 0;
  public static final int LINK = 28;
  public static final int TRUE = 58;
  public static final int SIZE = 20;
  public static final int COMILLA = 56;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int CADENA = 57;
  public static final int MENOS = 53;
  public static final int MAYOR_QUE = 51;
  public static final int ICON = 27;
  public static final int NAME = 21;
  public static final int COLOR = 13;
  public static final int BARRA = 44;
  public static final int HEADER = 5;
  public static final int ELSE = 30;
  public static final int TITLE = 2;
  public static final int PARENTESIS_C = 39;
  public static final int FONT_FAMILY = 8;
  public static final int X_AXIS_LABEL = 15;
  public static final int WHILE = 32;
  public static final int PARENTESIS_A = 38;
  public static final int MAYOR_IGUAL = 46;
  public static final int DASHED = 25;
  public static final int FOOTER = 6;
  public static final int HEXADECIMAL = 55;
  public static final int MENOR_QUE = 50;
  public static final int VALUE = 12;
  public static final int MENOR_IGUAL = 45;
  public static final int FALSE = 59;
  public static final int LABEL = 26;
  public static final int DO = 33;
  public static final int MAS = 52;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TITLE",
  "DESCRIPTION",
  "KEYWORDS",
  "HEADER",
  "FOOTER",
  "BACKGROUND_COLOR",
  "FONT_FAMILY",
  "FONT_SIZE",
  "DATA",
  "CATEGORY",
  "VALUE",
  "COLOR",
  "CHART",
  "X_AXIS_LABEL",
  "Y_AXIS_LABEL",
  "LEGEND_POSITION",
  "X",
  "Y",
  "SIZE",
  "NAME",
  "POINTS",
  "LINE_STYLE",
  "SOLID",
  "DASHED",
  "LABEL",
  "ICON",
  "LINK",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "DO",
  "ASTERISCO",
  "COMA",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "BARRA",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "DIFERENTE",
  "IGUAL",
  "IGUAL_IGUAL",
  "MENOR_QUE",
  "MAYOR_QUE",
  "MAS",
  "MENOS",
  "IDENTIFICADOR",
  "HEXADECIMAL",
  "COMILLA",
  "CADENA",
  "TRUE",
  "FALSE",
  "CONSTANTE"
  };
}

